### ISSUE TITLE
Follower's "Amount of Turn" entries do not enumerate properly

### ISSUE THREAD

**Issue by auppal** [ballroomfocus/danceinfo#2]
Example: Entry for Follower's part of 1-2-3 of Natural turn has "Commence to Turn" on step 1, but displayed table says "Commence to turn to R between 2 & 3". Similarly for the full Natural turn, Follower's "Commence to Turn" on step 1 renders as "Commence to Trun to R at end of 4".

**Comment by paulbohman** [comment]
Fixed. I forgot to reset the value after running through the leader's parts. The code resets that value now.
